version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.0-python3.10
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Jakarta
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    PYTHONPATH: /opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./Scraping:/opt/airflow/Scraping
    - ./output:/opt/airflow/output
    - ./requirements.txt:/requirements.txt
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: >
      bash -c "
      pip install -r /requirements.txt &&
      python -c 'import nltk; nltk.download(\"punkt\")' &&
      airflow db init &&
      airflow users create
        --username airflow
        --password airflow
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@example.com
      "

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      python -c 'import nltk; nltk.download(\"punkt\")' &&
      airflow webserver
      "

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      python -c 'import nltk; nltk.download(\"punkt\")' &&
      airflow scheduler
      "

volumes:
  postgres-db-volume:
